// Pure filesystem helpers: recursively finding source markdown files and
// writing output files, all path handling relative-string based (no
// ballerina/ai dependency), mirroring bundle_nav.bal's separation of concerns
// in the sibling navigator agent.

import ballerina/file;
import ballerina/io;

// Recursively finds every "*.md" file under `root`, skipping OKF's reserved
// filenames (index.md, log.md -- see SPEC.md section 3.1) since those are
// generated by this tool, not converted from source. Returns paths relative
// to `root`, using "/" separators regardless of OS.
isolated function findMarkdownFiles(string root) returns string[]|error {
    string[] results = [];
    check collectMarkdownFiles(root, root, results);
    return results;
}

isolated function collectMarkdownFiles(string root, string currentDir, string[] results) returns error? {
    file:MetaData[] entries = check file:readDir(currentDir);
    foreach file:MetaData entry in entries {
        if entry.dir {
            check collectMarkdownFiles(root, entry.absPath, results);
            continue;
        }
        string name = check file:basename(entry.absPath);
        if !name.endsWith(".md") || name == "index.md" || name == "log.md" {
            continue;
        }
        string relativePath = check file:relativePath(root, entry.absPath);
        results.push(toForwardSlashes(relativePath));
    }
}

isolated function toForwardSlashes(string path) returns string {
    return replaceLiteral(path, "\\", "/");
}

// Literal (non-regex) substring replace, since `string` has no such method.
isolated function replaceLiteral(string value, string target, string replacement) returns string {
    if !value.includes(target) {
        return value;
    }
    string result = "";
    string remaining = value;
    while true {
        int? matchIndex = remaining.indexOf(target);
        if matchIndex is () {
            result = result + remaining;
            break;
        }
        result = result + remaining.substring(0, matchIndex) + replacement;
        remaining = remaining.substring(matchIndex + target.length());
    }
    return result;
}

isolated function readSourceFile(string root, string relativePath) returns string|error {
    string fullPath = check file:joinPath(root, relativePath);
    return io:fileReadString(fullPath);
}

isolated function writeOutputFile(string bundleRootPath, string relativePath, string content) returns error? {
    string parentDir = dirnameOfRel(relativePath);
    string parentDirAbs = parentDir == "" ? bundleRootPath : check file:joinPath(bundleRootPath, parentDir);
    if !(check file:test(parentDirAbs, file:EXISTS)) {
        check file:createDir(parentDirAbs, file:RECURSIVE);
    }
    string fullPath = check file:joinPath(bundleRootPath, relativePath);
    check io:fileWriteString(fullPath, content);
}

// "apis/foo.md" -> "apis"; "apis" -> ""; "" -> "".
isolated function dirnameOfRel(string relativePath) returns string {
    int? separatorIndex = relativePath.lastIndexOf("/");
    if separatorIndex is () {
        return "";
    }
    return relativePath.substring(0, separatorIndex);
}

// "apis/foo.md" -> "foo.md"; "foo.md" -> "foo.md".
isolated function basenameOfRel(string relativePath) returns string {
    int? separatorIndex = relativePath.lastIndexOf("/");
    if separatorIndex is () {
        return relativePath;
    }
    return relativePath.substring(separatorIndex + 1);
}

// SPEC.md section 2: Concept ID is the path of the concept's file within the
// bundle, with the .md suffix removed. "apis/foo.md" -> "apis/foo".
isolated function conceptIdOf(string relativePath) returns string {
    if relativePath.endsWith(".md") {
        return relativePath.substring(0, relativePath.length() - 3);
    }
    return relativePath;
}
